#!/usr/bin/env bash
# Script to install and configure NGINX

sudo apt-get -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > index.html
sudo mv index.html /var/www/html/
sudo service nginx restart