#!/usr/bin/env bash
# Install the ufw firewall and setup a few rules

sudo apt-get update
sudo apt-get install ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable